import { Producto } from "../interfaces/producto-interface";

export const INVENTARIO: Producto[] = [
  { id: 1, nombre: 'Cuaderno', precio: 15000, descripcion: 'Cuaderno de tapa dura, 100 hojas' },
  { id: 2, nombre: 'Lápiz', precio: 2500, descripcion: 'Lápiz HB con goma de borrar' },
  { id: 3, nombre: 'Bolígrafo', precio: 6000, descripcion: 'Bolígrafo de tinta negra' },
  { id: 4, nombre: 'Regla', precio: 10000, descripcion: 'Regla de plástico transparente, 30 cm' },
  { id: 5, nombre: 'Goma de borrar', precio: 3000, descripcion: 'Goma de borrar blanca' },
  { id: 6, nombre: 'Marcadores', precio: 20000, descripcion: 'Conjunto de 12 marcadores de colores' },
  { id: 7, nombre: 'Libreta', precio: 15000, descripcion: 'Libreta de espiral, cuadrícula' },
  { id: 8, nombre: 'Cinta adhesiva', precio: 5000, descripcion: 'Rollo de cinta adhesiva transparente' },
  { id: 9, nombre: 'Tijeras', precio: 12000, descripcion: 'Tijeras de acero inoxidable, punta roma' },
  { id: 10, nombre: 'Post-its', precio: 8000, descripcion: 'Bloque de notas adhesivas, varios colores' },
  { id: 11, nombre: 'Folder', precio: 10000, descripcion: 'Folder de plástico, tamaño carta' },
  { id: 12, nombre: 'Borrador', precio: 2500, descripcion: 'Borrador rectangular de color blanco' },
  { id: 13, nombre: 'Portaminas', precio: 14000, descripcion: 'Portaminas con minas de 0.7mm' },
  { id: 14, nombre: 'Pegamento', precio: 8000, descripcion: 'Pegamento en barra' },
  { id: 15, nombre: 'Carpeta', precio: 17000, descripcion: 'Carpeta de argollas, tamaño oficio' },
  { id: 16, nombre: 'Estuche para lápices', precio: 20000, descripcion: 'Estuche con cierre para lápices y bolígrafos' },
  { id: 17, nombre: 'Papel bond', precio: 30000, descripcion: 'Paquete de 100 hojas de papel bond' },
  { id: 18, nombre: 'Clips', precio: 2000, descripcion: 'Caja de clips metálicos' },
  { id: 19, nombre: 'Resaltadores', precio: 12000, descripcion: 'Juego de 4 resaltadores fluorescentes' },
  { id: 20, nombre: 'Papel de colores', precio: 35000, descripcion: 'Paquete de 50 hojas de papel de colores' },
  { id: 21, nombre: 'Caja de lápices de colores', precio: 40000, descripcion: 'Caja de 24 lápices de colores' },
  { id: 22, nombre: 'Agenda', precio: 30000, descripcion: 'Agenda semanal con tapa dura' },
  { id: 23, nombre: 'Grapadora', precio: 15000, descripcion: 'Grapadora de escritorio, capacidad para 50 hojas' },
  { id: 24, nombre: 'Pizarra blanca', precio: 50000, descripcion: 'Pizarra blanca magnética, 60x90 cm' },
  { id: 25, nombre: 'Corrector líquido', precio: 6000, descripcion: 'Corrector líquido de secado rápido' },
  { id: 26, nombre: 'Perforadora', precio: 25000, descripcion: 'Perforadora de papel, 3 agujeros' },
  { id: 27, nombre: 'Calculadora científica', precio: 70000, descripcion: 'Calculadora científica con funciones avanzadas' },
  { id: 28, nombre: 'Bandejas para documentos', precio: 15000, descripcion: 'Juego de 3 bandejas apilables' },
  { id: 29, nombre: 'Pegamento en barra', precio: 8000, descripcion: 'Pegamento en barra sin solventes' },
  { id: 30, nombre: 'Organizador de escritorio', precio: 25000, descripcion: 'Organizador de escritorio con compartimentos' },
  { id: 31, nombre: 'Bolsas ziploc', precio: 4000, descripcion: 'Paquete de 50 bolsas ziploc, tamaño sandwich' },
  { id: 32, nombre: 'Cinta correctora', precio: 2500, descripcion: 'Cinta correctora de 5mm de ancho' },
  { id: 33, nombre: 'Carpeta expandible', precio: 13000, descripcion: 'Carpeta expandible con solapas' },
  { id: 34, nombre: 'Marcadores permanentes', precio: 10000, descripcion: 'Juego de 6 marcadores permanentes' },
  { id: 35, nombre: 'Bolígrafos de gel', precio: 12000, descripcion: 'Paquete de 3 bolígrafos de gel' },
];
